// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingBuddy.DAL;

#nullable disable

namespace ShoppingBuddy.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingBuddy.DAL.Entities.Shopper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("shoppers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            Image = "/images/shoppers/john-doe.png",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Emily",
                            Image = "/images/shoppers/emily-johnson.png",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Benjamin",
                            Image = "/images/shoppers/benjamin-smith.png",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ava",
                            Image = "/images/shoppers/ava-williams.png",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Olivia",
                            Image = "/images/shoppers/olivia-davis.png",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("ShoppingBuddy.DAL.Entities.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("shopping_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/images/shopping-items/milk.png",
                            Title = "Milk"
                        },
                        new
                        {
                            Id = 2,
                            Image = "/images/shopping-items/apple-juice.png",
                            Title = "Apple juice"
                        },
                        new
                        {
                            Id = 3,
                            Image = "/images/shopping-items/chocolate.png",
                            Title = "Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            Image = "/images/shopping-items/chips.png",
                            Title = "Chips"
                        },
                        new
                        {
                            Id = 5,
                            Image = "/images/shopping-items/bread.png",
                            Title = "Bread"
                        });
                });

            modelBuilder.Entity("ShoppingBuddy.DAL.Entities.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ShopperId")
                        .HasColumnType("int")
                        .HasColumnName("shopper_id");

                    b.Property<int>("ShoppingItemId")
                        .HasColumnType("int")
                        .HasColumnName("shopping_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ShopperId");

                    b.HasIndex("ShoppingItemId");

                    b.ToTable("shopping_list_items", (string)null);
                });

            modelBuilder.Entity("ShoppingBuddy.DAL.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("ShoppingBuddy.DAL.Entities.Shopper", "Shopper")
                        .WithMany()
                        .HasForeignKey("ShopperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingBuddy.DAL.Entities.ShoppingItem", "ShoppingItem")
                        .WithMany()
                        .HasForeignKey("ShoppingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shopper");

                    b.Navigation("ShoppingItem");
                });
#pragma warning restore 612, 618
        }
    }
}
